odd_path = {
    'PreGame': {
        'HA': '讓分',
        'OU': '大小',
        'Others-Correct Score': '正確比分',
        'Others-CornerHA': '角球讓分',
        'Others-CornerOU': '角球大小',
        'Others-Half Time/Full Time': '半全場',
        'Others-HalfOU': '上半場大小',
        'Others-HalfHA': '上半場讓分盤',
        'Others-2nd HalfHA': '下半場讓分盤',
        'Others-2nd HalfOU': '下半大小盤',
        'Others-1st QuarterHA': '第一節讓分',
        'Others-1st QuarterOU': '第一節大小',
        'Others-2nd QuarterHA': '第二節讓分',
        'Others-2nd QuarterOU': '第二節大小',
        'Others-3rd QuarterHA': '第三節讓分',
        'Others-3rd QuarterOU': '第三節大小',
        'Others-4th QuarterHA': '第四節讓分',
        'Others-4th QuarterOU': '第四節大小',
        'Others-1~3InnHA': '1-3局讓分',
        'Others-1~3InnOU': '1-3局大小盤',
        'Others-1~4 1/2InnHA': '1-4 1/2 局讓分',
        'Others-1~4 1/2InnOU': '1-4 1/2局大小',
        'Others-1~7InnHA': '1-7局讓分',
        'Others-1~7InnOU': '1-7局大小盤',
        'Others-1InnHA': '第1局讓分',
        'Others-1InnOU': '第1局大小',
        'Others-1~3InnOdd/Even': '1-3局單雙',
        'Others-1~7InnOdd/Even': '1-7局單雙',
        'Others-T1 Score': '主隊得分大小',
        'Others-T2 Score': '客隊得分大小',
        'Others-0~15minOU': '1-15分鐘:總進球數大小',
        'Others-15~30minOU': '15~30分鐘大小',
        'Others-30~45minOU': '30~45分鐘大小',
        'Others-45~60minOU': '45~60分鐘大小',
        'Others-60~75minOU': '60~75分鐘大小',
        'Others-75~90minOU': '75~90分鐘大小',
        'Others-0~15minHA': '0~15分鐘讓分',
        'Others-15~30minHA': '15~30分鐘讓分',
        'Others-30~45minHA': '30~45分鐘讓分',
        'Others-45~60minHA': '45~60分鐘讓分',
        'Others-60~75minHA': '60~75分鐘讓分',
        'Others-75~90minHA': '75~90分鐘讓分',
        'Others-CornerOdd/Even': '角球單雙',
        'Others-Total Score': '全場總分',
        'Others-Half Total Score': '上半場總入球數',
        'Others-FirstScore': '先得分',
        'Others-LastScore': '最後得分',
        'Others-TotalHitOU': '安打總數',
        'Others-RunsHitsErrorsOU': '得分安打失誤總數',
        'Others-HalfHighScore': '上半得分最高隊伍',
        'Others-5PointsFirst': '最先得5分',
        'Others-10PointsFirst': '最先得10分',
        'Others-15PointsFirst': '最先得15分',
        'Others-20PointsFirst': '最先得20分',
        'Others-30PointsFirst': '最先得30分',
        'Others-40PointsFirst': '最先得40分',
        'Others-50PointsFirst': '最先得50分',
        'Others-3pointsHA': '3分球數讓分',
        'Others-3pointsOU': '3分球數大小',
        'Others-3pointsOdd/Even': '3分球數單雙',
        'Others-T1ScoreOdd/Even': '主隊全場總得分單雙',
        'Others-T1HalfScore': '主隊半場總得分',
        'Others-T1HalfScoreOdd/Even': '主隊半場總得分單雙',
        'Others-T11st QuarterScore': '主隊第一節總得分',
        'Others-T11st QuarterScoreOdd/Even': '主隊第一節總得分單雙',
        'Others-T12nd QuarterScore': '主隊第二節總得分',
        'Others-T12nd QuarterScoreOdd/Even': '主隊第二節總得分單雙',
        'Others-T13rd QuarterScore': '主隊第三節總得分',
        'Others-T13rd QuarterScoreOdd/Even': '主隊第三節總得分單雙',
        'Others-T14th QuarterScore': '主隊第四節總得分',
        'Others-T14th QuarterScoreOdd/Even': '主隊第四節分數單雙',
        'Others-T2ScoreOdd/Even': '客隊總得分單雙',
        'Others-T2HalfScore': '客隊半場總得分',
        'Others-T2HalfScoreOdd/Even': '客隊半場總得分單雙',
        'Others-T21st QuarterScore': '客隊第一節總得分',
        'Others-T21st QuarterScoreOdd/Even': '客隊第一節總得分單雙',
        'Others-T22nd QuarterScore': '客隊第二節總得分',
        'Others-T22nd QuarterScoreOdd/Even': '客隊第二節總得分單雙',
        'Others-T23rd QuarterScore': '客隊第三節總得分',
        'Others-T23rd QuarterScoreOdd/Even': '客隊第三節總得分單雙',
        'Others-T24th QuarterScore': '客隊第四節總得分',
        'Others-T24th QuarterScoreOdd/Even': '客隊第四節總得分單雙',
        'Others-AssistsHA': '助攻讓分',
        'Others-AssistsOU': '助攻大小',
        'Others-AssistsHAOdd/Even': '助攻單雙',
        'Others-BouncesHA': '籃板讓分',
        'Others-BouncesOU': '籃板大小',
        'Others-BouncesOdd/Even': '籃板單雙',
        'Others-StealsHA': '抄截讓分',
        'Others-StealsOU': '抄截大小',
        'Others-StealsOdd/Even': '抄截單雙',
        'Others-First3Point': '第一顆3分球',
        'Others-Second3Point': '第二顆3分球',
        'Others-Third3Point': '第三顆3分球',
        'Others-Fourth3Point': '第四顆3分球',
        'Others-Fifth3Point': '第五顆3分球',
        'Others-Last3Point': '最後一顆3分球',
        'Others-FirstConsultation': '發起挑戰',
        'Others-FirstFreethrowScore': '罰球先得分',
        'Others-LastFreethrowScore': '罰球最後得分',
        'Others-HalfLastScore': '上半場最後得分',
        'Others-2ndHalfFirstScore': '下半場先得分',
        'Others-1stQuarterLastScore': '第一節最後得分',
        'Others-2ndQuarterFirstScore': '第二節先得分',
        'Others-3rdQuarterLastScore': '第三節最後得分',
        'Others-4thQuarterFirstScore': '第四節先得分',
        'Others-1stQuarter5PointsFirst': '第一節先得5分',
        'Others-1stQuarter10PointsFirst': '第一節先得10分',
        'Others-1stQuarter15PointsFirst': '第一節先得15分',
        'Others-2ndQuarter5PointsFirst': '第二節先得5分',
        'Others-2ndQuarter10PointsFirst': '第二節先得10分',
        'Others-2ndQuarter15PointsFirst': '第二節先得15分',
        'Others-3rdQuarter5PointsFirst': '第三節先得5分',
        'Others-3rdQuarter10PointsFirst': '第三節先得10分',
        'Others-3rdQuarter15PointsFirst': '第三節先得15分',
        'Others-4thQuarter5PointsFirst': '第四節先得5分',
        'Others-4thQuarter10PointsFirst': '第四節先得10分',
        'Others-4thQuarter15PointsFirst': '第四節先得15分',
        'Others-Odd/Even': '全場單雙',
        'Others-HalfOdd/Even': '半場單雙',
        'Others-1st QuarterOdd/Even': '第一節單雙',
        'Others-2nd QuarterOdd/Even': '第二節單雙',
        'Others-3rd QuarterOdd/Even': '第三節單雙',
        'Others-4th QuarterOdd/Even': '第四節單雙',
        'Others-CardHA': '罰牌讓分',
        'Others-CardOU': '罰牌數大小',
        'Others-CardOdd/Even': '罰牌單雙',
        'Others-HalfCorrect Score': '上半場正確比分',
        'Others-1st SetGameHA': '第一局讓分(網球)',
        'Others-2nd SetGameHA': '第二局讓分(網球)',
        'Others-3rd SetGameHA': '第三局讓分(網球)',
        'Others-4th SetGameHA': '第四局讓分(網球)',
        'Others-5th SetGameHA': '第五局讓分(網球)',
        'Others-6th SetGameHA': '第六局讓分(網球)',
        'Others-7th SetGameHA': '第七局讓分(網球)',
        'Others-1st PointHA': '第一局讓分(桌球、排球、羽球)',
        'Others-2nd PointHA': '第二局讓分(桌球、排球、羽球)',
        'Others-3rd PointHA': '第三局讓分(桌球、排球、羽球)',
        'Others-4th PointHA': '第四局讓分(桌球、排球、羽球)',
        'Others-5 PointHA': '第五局讓分(桌球、排球、羽球)',
        'Others-6 PointHA': '第六局讓分(桌球、排球、羽球)',
        'Others-7 PointHA': '第七局讓分(桌球、排球、羽球)',
        'Others-1st SetGameOU': '第一局大小(網球)',
        'Others-2nd SetGameOU': '第二局大小(網球)',
        'Others-3rd SetGameOU': '第三局大小(網球)',
        'Others-4th SetGameOU': '第四局大小(網球)',
        'Others-5th SetGameOU': '第五局大小(網球)',
        'Others-6th SetGameOU': '第六局大小(網球)',
        'Others-7th SetGameOU': '第七局大小(網球)',
        'Others-1st PointOU': '第一局大小(桌球、排球、羽球)',
        'Others-2nd PointOU': '第二局大小(桌球、排球、羽球)',
        'Others-3rd PointOU': '第三局大小(桌球、排球、羽球)',
        'Others-4th PointOU': '第四局大小(桌球、排球、羽球)',
        'Others-5 PointOU': '第五局大小(桌球、排球、羽球)',
        'Others-6 PointOU': '第六局大小(桌球、排球、羽球)',
        'Others-7 PointOU': '第七局大小(桌球、排球、羽球)',
        'Others-1st PointOdd/Even': '第一局單雙(桌球、排球、羽球)',
        'Others-2nd PointOdd/Even': '第二局單雙(桌球、排球、羽球)',
        'Others-3rd PointOdd/Even': '第三局單雙(桌球、排球、羽球)',
        'Others-4th PointOdd/Even': '第四局單雙(桌球、排球、羽球)',
        'Others-5 PointOdd/Even': '第五局單雙(桌球、排球、羽球)',
        'Others-6 PointOdd/Even': '第六局單雙(桌球、排球、羽球)',
        'Others-7 PointOdd/Even': '第七局單雙(桌球、排球、羽球)',
        'Others-GameHA': '讓分(網球)',
        'Others-PointHA': '讓分(桌球、排球、羽球)',
        'Others-GameOU': '大小(網球)',
        'Others-CornerHalfHA': '上半場角球讓分',
        'Others-CornerHalfOU': '上半場角球大小',
        'Others-CornerHalfOdd/Even': '上半場角球單雙',
        'Others-CardHalfHA': '上半場罰牌數讓分',
        'Others-CardHalfOU': '上半場罰牌數大小',
        'Others-CardHalfOdd/Even': '上半場罰牌數單雙',
        'Others-1st MapHA': '第一張地圖讓分',
        'Others-1st MapOU': '第一張地圖大小',
        'Others-2nd MapHA': '第二張地圖讓分',
        'Others-2nd MapOU': '第二張地圖大小',
        'Others-3rd MapHA': '第三張地圖讓分',
        'Others-3rd MapOU': '第三張地圖大小',
        'Others-4th MapHA': '第四張地圖讓分',
        'Others-4th MapOU': '第四張地圖大小',
        'Others-5th MapHA': '第五張地圖讓分',
        'Others-5th MapOU': '第五張地圖大小',
        'Others-1st MapKillHA': '第一張地圖擊殺讓分',
        'Others-2nd MapKillHA': '第二張地圖擊殺讓分',
        'Others-3rd MapKillHA': '第三張地圖擊殺讓分',
        'Others-4th MapKillHA': '第四張地圖擊殺讓分',
        'Others-5th MapKillHA': '第五張地圖擊殺讓分',
        'Others-6th MapKillHA': '第六張地圖擊殺讓分',
        'Others-7th MapKillHA': '第七張地圖擊殺讓分',
        'Others-1st MapKillOU': '第一張地圖擊殺大小',
        'Others-2nd MapKillOU': '第二張地圖擊殺大小',
        'Others-3rd MapKillOU': '第三張地圖擊殺大小',
        'Others-4th MapKillOU': '第四張地圖擊殺大小',
        'Others-5th MapKillOU': '第五張地圖擊殺大小',
        'Others-6th MapKillOU': '第六張地圖擊殺大小',
        'Others-7th MapKillOU': '第七張地圖擊殺大小',
        'Others-1st MapFinTime': '第一張地圖結束時間',
        'Others-2nd MapFinTime': '第二張地圖結束時間',
        'Others-3rd MapFinTime': '第三張地圖結束時間',
        'Others-4th MapFinTime': '第四張地圖結束時間',
        'Others-5th MapFinTime': '第五張地圖結束時間',
        'Others-1st MapFirstBlood': '第一張地圖首殺',
        'Others-2nd MapFirstBlood': '第二張地圖首殺',
        'Others-3rd MapFirstBlood': '第三張地圖首殺',
        'Others-4th MapFirstBlood': '第四張地圖首殺',
        'Others-5th MapFirstBlood': '第五張地圖首殺',
        'Others-6th MapFirstBlood': '第六張地圖首殺',
        'Others-7th MapFirstBlood': '第七張地圖首殺',
        'Others-1st MapTowerHA': '第一張地圖防禦塔讓分',
        'Others-2nd MapTowerHA': '第二張地圖防禦塔讓分',
        'Others-3rd MapTowerHA': '第三張地圖防禦塔讓分',
        'Others-4th MapTowerHA': '第四張地圖防禦塔讓分',
        'Others-5th MapTowerHA': '第五張地圖防禦塔讓分',
        'Others-6th MapTowerHA': '第六張地圖防禦塔讓分',
        'Others-7th MapTowerHA': '第七張地圖防禦塔讓分',
        'Others-1st MapTowerOU': '第一張地圖防禦塔大小',
        'Others-2nd MapTowerOU': '第二張地圖防禦塔大小',
        'Others-3rd MapTowerOU': '第三張地圖防禦塔大小',
        'Others-4th MapTowerOU': '第四張地圖防禦塔大小',
        'Others-5th MapTowerOU': '第五張地圖防禦塔大小',
        'Others-6th MapTowerOU': '第六張地圖防禦塔大小',
        'Others-7th MapTowerOU': '第七張地圖防禦塔大小',
        'Others-1st MapDragonHA': '第一張地圖小龍讓分',
        'Others-2nd MapDragonHA': '第二張地圖小龍讓分',
        'Others-3rd MapDragonHA': '第三張地圖小龍讓分',
        'Others-4th MapDragonHA': '第四張地圖小龍讓分',
        'Others-5th MapDragonHA': '第五張地圖小龍讓分',
        'Others-6th MapDragonHA': '第六張地圖小龍讓分',
        'Others-7th MapDragonHA': '第七張地圖小龍讓分',
        'Others-1st MapDragonOU': '第一張地圖小龍大小',
        'Others-2nd MapDragonOU': '第二張地圖小龍大小',
        'Others-3rd MapDragonOU': '第三張地圖小龍大小',
        'Others-4th MapDragonOU': '第四張地圖小龍大小',
        'Others-5th MapDragonOU': '第五張地圖小龍大小',
        'Others-6th MapDragonOU': '第六張地圖小龍大小',
        'Others-7th MapDragonOU': '第七張地圖小龍大小',
        'Others-1st MapBaronHA': '第一張地圖巴龍讓分',
        'Others-2nd MapBaronHA': '第二張地圖巴龍讓分',
        'Others-3rd MapBaronHA': '第三張地圖巴龍讓分',
        'Others-4th MapBaronHA': '第四張地圖巴龍讓分',
        'Others-5th MapBaronHA': '第五張地圖巴龍讓分',
        'Others-6th MapBaronHA': '第六張地圖巴龍讓分',
        'Others-7th MapBaronHA': '第七張地圖巴龍讓分',
        'Others-1st MapBaronOU': '第一張地圖巴龍大小',
        'Others-2nd MapBaronOU': '第二張地圖巴龍大小',
        'Others-3rd MapBaronOU': '第三張地圖巴龍大小',
        'Others-4th MapBaronOU': '第四張地圖巴龍大小',
        'Others-5th MapBaronOU': '第五張地圖巴龍大小',
        'Others-6th MapBaronOU': '第六張地圖巴龍大小',
        'Others-7th MapBaronOU': '第七張地圖巴龍大小',
        'Others-1st MapKill5First': '第一張地圖先5殺',
        'Others-2nd MapKill5First': '第二張地圖先5殺',
        'Others-3rd MapKill5First': '第三張地圖先5殺',
        'Others-4th MapKill5First': '第四張地圖先5殺',
        'Others-5th MapKill5First': '第五張地圖先5殺',
        'Others-6th MapKill5First': '第六張地圖先5殺',
        'Others-7th MapKill5First': '第七張地圖先5殺',
        'Others-1st MapFirstInhibitor': '第一張地圖首座水晶塔',
        'Others-2nd MapFirstInhibitor': '第二張地圖首座水晶塔',
        'Others-3rd MapFirstInhibitor': '第三張地圖首座水晶塔',
        'Others-4th MapFirstInhibitor': '第四張地圖首座水晶塔',
        'Others-5th MapFirstInhibitor': '第五張地圖首座水晶塔',
        'Others-6th MapFirstInhibitor': '第六張地圖首座水晶塔',
        'Others-7th MapFirstInhibitor': '第七張地圖首座水晶塔',
        'Others-1st MapFirstTower': '第一張地圖首塔',
        'Others-2nd MapFirstTower': '第二張地圖首塔',
        'Others-3rd MapFirstTower': '第三張地圖首塔',
        'Others-4th MapFirstTower': '第四張地圖首塔',
        'Others-5th MapFirstTower': '第五張地圖首塔',
        'Others-6th MapFirstTower': '第六張地圖首塔',
        'Others-7th MapFirstTower': '第七張地圖首塔',
        'Others-1st MapFirstDragon': '第一張地圖第一隻小龍',
        'Others-2nd MapFirstDragon': '第二張地圖第一隻小龍',
        'Others-3rd MapFirstDragon': '第三張地圖第一隻小龍',
        'Others-4th MapFirstDragon': '第四張地圖第一隻小龍',
        'Others-5th MapFirstDragon': '第五張地圖第一隻小龍',
        'Others-6th MapFirstDragon': '第六張地圖第一隻小龍',
        'Others-7th MapFirstDragon': '第七張地圖第一隻小龍',
        'Others-1st MapFirstBaron': '第一張地圖第一隻巴龍(大龍)',
        'Others-2nd MapFirstBaron': '第二張地圖第一隻巴龍(大龍)',
        'Others-3rd MapFirstBaron': '第三張地圖第一隻巴龍(大龍)',
        'Others-4th MapFirstBaron': '第四張地圖第一隻巴龍(大龍)',
        'Others-5th MapFirstBaron': '第五張地圖第一隻巴龍(大龍)',
        'Others-6th MapFirstBaron': '第六張地圖第一隻巴龍(大龍)',
        'Others-7th MapFirstBaron': '第七張地圖第一隻巴龍(大龍)',
        'Others-1st MapFirstNexusTower': '第一張地圖首座兵營塔',
        'Others-2nd MapFirstNexusTower': '第二張地圖首座兵營塔',
        'Others-3rd MapFirstNexusTower': '第三張地圖首座兵營塔',
        'Others-4th MapFirstNexusTower': '第四張地圖首座兵營塔',
        'Others-5th MapFirstNexusTower': '第五張地圖首座兵營塔',
        'Others-6th MapFirstNexusTower': '第六張地圖首座兵營塔',
        'Others-7th MapFirstNexusTower': '第七張地圖首座兵營塔',
        'Others-1st MapFirstMidTower': '第一張地圖首座中路塔',
        'Others-2nd MapFirstMidTower': '第二張地圖首座中路塔',
        'Others-3rd MapFirstMidTower': '第三張地圖首座中路塔',
        'Others-4th MapFirstMidTower': '第四張地圖首座中路塔',
        'Others-5th MapFirstMidTower': '第五張地圖首座中路塔',
        'Others-6th MapFirstMidTower': '第六張地圖首座中路塔',
        'Others-7th MapFirstMidTower': '第七張地圖首座中路塔',
        'Others-PointOU': '全場得分大小(桌球 排球 羽球)',
        'Others-Win': 'KO勝利/判決勝利(格鬥)',
        'Others-Double Chance': '雙勝彩',
        'Others-T1 Team Total Goals': '主隊總入球數',
        'Others-T2 Team Total Goals': '客隊總入球數',
        'Others-HalfT1 Team Total Goals': '上半場主隊總入球數',
        'Others-HalfT2 Team Total Goals': '上半場客隊總入球數',
        'Others-Both Teams To Score': '雙方球隊進球',
        'Others-HalfBoth Teams To Score': '上半場雙方球隊進球',
        'Others-0~30minHA': '1-30分鐘:讓球',
        'Others-0~60minHA': '1-60分鐘:讓球',
        'Others-0~75minHA': '1-75分鐘:讓球',
        'Others-T10~15minOU': '介於開賽1-15分鐘主隊進球數大小',
        'Others-T20~15minOU': '介於開賽1-15分鐘客隊進球數大小',
        'Others-T10~30minOU': '介於開賽1-30分鐘主隊進球數大小',
        'Others-T20~30minOU': '介於開賽1-30分鐘客隊進球數大小',
        'Others-T10~60minOU': '介於開賽1-30分鐘主隊進球數大小',
        'Others-T20~60minOU': '介於開賽1-60分鐘客隊進球數大小',
        'Others-T10~75minOU': '介於開賽1-75分鐘主隊進球數大小',
        'Others-T20~75minOU': '介於開賽1-75分鐘客隊進球數大小',
        'Others-0~30minOU': '1-30分鐘:總進球數大小',
        'Others-0~60minOU': '1-60分鐘:總進球數大小',
        'Others-0~75minOU': '1-75分鐘:總進球數大小',
        'Others-0~15minBoth Teams to Score': '1-15分鐘兩隊皆進球',
        'Others-0~30minBoth Teams to Score': '1-30分鐘兩隊皆進球',
        'Others-0~60minBoth Teams to Score': '1-60分鐘兩隊皆進球',
        'Others-0~75minBoth Teams to Score': '1-75分鐘兩隊皆進球',
        'Others-YellowCardHalfHA': '黃牌數:上半場讓分盤',
        'Others-T1YellowCardHalfOU': '上半場主隊總黃牌數大小',
        'Others-T2YellowCardHalfOU': '上半場客隊總黃牌數大小',
        'Others-T1YellowCard2ndHalfOU': '下半場主隊總黃牌數大小',
        'Others-T2YellowCard2ndHalfOU': '下半場客隊總黃牌數大小',
        'Others-YellowCardHalfOU': '上半場總黃牌數大小',
        'Others-A Red Card in the Match': '全場是否出現紅牌',
        'Others-First Yellow Card': '比賽中第一次收到黃牌的隊',
        'Others-Last Yellow Card': '比賽中最後收到黃牌的隊',
        'Others-Yellow Cards Double Chance': '全場總黃牌數:雙勝',
        'Others-T1YellowCardOU': '全場主隊總黃牌數大小',
        'Others-T2YellowCardOU': '全場客隊總黃牌數大小',
        'Others-YellowCardOU': '全場黃牌數大小',
        'Others-YellowCardHA': '全場黃牌數:讓牌',
        'Others-Corner2ndHalfOU': '下半場總角球數大小',
        'Others-T1HalfCornerOU': '上半場主隊總角球數大小',
        'Others-T2HalfCornerOU': '上半場客隊總角球數大小',
        'Others-T12ndHalfCornerOU': '下半場主隊總數大小',
        'Others-T22ndHalfCornerOU': '下半場客隊總數大小',
        'Others-First Corner': '獲得罰角球權的第一隊',
        'Others-Last Corner': '獲得罰角球權的最後隊',
        'Others-T1CornerOU': '全場主隊總角球數大小',
        'Others-T2CornerOU': '全場客隊總角球數大小',
        'Others-3wayCornerOU': '角球數大小(3選項)',
        'Others-Corners Double Chance': '全場總角球數:雙勝彩',
        'Others-Half With The Most Corners': '半場最多角球數',
        'Others-2PointsFirst': '先進兩球',
        'Others-3PointsFirst': '先進三球',
        'Others-FirstCard': '第一張罰牌',
        'Others-LastCard': '最後一張罰牌'
    },
    'InPlay': {
        'RBHA': '走地讓分',
        'RBOU': '走地大小',
        'RBOthers-HalfRBHA': '上半場讓分盤',
        'RBOthers-HalfRBOU': '上半場大小',
        'RBOthers-1st QuarterRBHA': '第一節讓分',
        'RBOthers-1st QuarterRBOU': '第一節大小',
        'RBOthers-2nd QuarterRBHA': '第二節讓分',
        'RBOthers-2nd QuarterRBOU': '第二節大小',
        'RBOthers-3rd QuarterRBHA': '第三節讓分',
        'RBOthers-3rd QuarterRBOU': '第三節大小',
        'RBOthers-4th QuarterRBHA': '第四節讓分',
        'RBOthers-4th QuarterRBOU': '第四節大小',
        'RBOthers-RBOdd/Even': '單雙',
        'RBOthers-1~3InnRBHA': '1-3局讓分',
        'RBOthers-1~3InnRBOU': '1-3局大小',
        'RBOthers-1~7InnRBHA': '1-7局讓分',
        'RBOthers-1~7InnRBOU': '1-7局大小',
        'RBOthers-1InnRBHA': '第1局讓分',
        'RBOthers-2InnRBHA': '第2局讓分',
        'RBOthers-3InnRBHA': '第3局讓分',
        'RBOthers-4InnRBHA': '第4局讓分',
        'RBOthers-5InnRBHA': '第5局讓分',
        'RBOthers-6InnRBHA': '第6局讓分',
        'RBOthers-7InnRBHA': '第7局讓分',
        'RBOthers-8InnRBHA': '第8局讓分',
        'RBOthers-9InnRBHA': '第9局讓分',
        'RBOthers-1InnRBOU': '第1局大小',
        'RBOthers-2InnRBOU': '第2局大小',
        'RBOthers-3InnRBOU': '第3局大小',
        'RBOthers-4InnRBOU': '第4局大小',
        'RBOthers-5InnRBOU': '第5局大小',
        'RBOthers-6InnRBOU': '第6局大小',
        'RBOthers-7InnRBOU': '第7局大小',
        'RBOthers-8InnRBOU': '第8局大小',
        'RBOthers-9InnRBOU': '第9局大小',
        'RBOthers-3pointsRBHA': '3分球讓分',
        'RBOthers-3pointsRBOU': '3分球大小',
        'RBOthers-3pointsRBOdd/Even': '3分球單雙',
        'RBOthers-0~15minRBOU': '0~15分鐘大小',
        'RBOthers-15~30minRBOU': '15~30分鐘大小',
        'RBOthers-30~45minRBOU': '30~45分鐘大小',
        'RBOthers-45~60minRBOU': '45~60分鐘大小',
        'RBOthers-60~75minRBOU': '60~75分鐘大小',
        'RBOthers-75~90minRBOU': '75~90分鐘大小',
        'RBOthers-0~15minRBHA': '0~15分鐘讓分',
        'RBOthers-15~30minRBHA': '15~30分鐘讓分',
        'RBOthers-30~45minRBHA': '30~45分鐘讓分',
        'RBOthers-45~60minRBHA': '45~60分鐘讓分',
        'RBOthers-60~75minRBHA': '60~75分鐘讓分',
        'RBOthers-75~90minRBHA': '75~90分鐘讓分',
        'RBOthers-T1ScoreRBOU': '主隊分數大小',
        'RBOthers-T1ScoreRBOdd/Even': '主隊分數單雙',
        'RBOthers-T11stQuarterScoreRBOU': '主隊第一節分數大小',
        'RBOthers-T11stQuarterScoreRBOdd/Even': '主隊第一節分數單雙',
        'RBOthers-T2ScoreRBOU': '客隊分數大小',
        'RBOthers-T2ScoreRBOdd/Even': '客隊分數單雙',
        'RBOthers-T21stQuarterScoreRBOU': '客隊第一節分數大小',
        'RBOthers-T21stQuarterScoreRBOdd/Even': '客隊第一節分數單雙',
        'RBOthers-1st QuarterRBOdd/Even': '第一節分數單雙',
        'RBOthers-2nd QuarterRBOdd/Even': '第二節分數單雙',
        'RBOthers-3rd QuarterRBOdd/Even': '第三節分數單雙',
        'RBOthers-4th QuarterRBOdd/Even': '第四節分數單雙',
        'RBOthers-T12ndHalfScoreRBOdd/Even': '主隊半場分數單雙',
        'RBOthers-T22ndHalfScoreRBOdd/Even': '客隊半場分數單雙',
        'RBOthers-T12ndHalfScoreRBOU': '主隊半場分數大小',
        'RBOthers-T22ndHalfScoreRBOU': '客隊半場分數大小',
        'RBOthers-2nd HalfRBHA': '半場分數讓分',
        'RBOthers-2nd HalfRBOU': '半場分數大小',
        'RBOthers-T1HalfScoreRBOU': '主隊半場分數大小',
        'RBOthers-T2HalfScoreRBOU': '客隊半場分數大小',
        'RBOthers-T12nd QuarterScoreRBOU': '主隊第二節分數大小',
        'RBOthers-T22nd QuarterScoreRBOU': '客隊第二節分數大小',
        'RBOthers-T13rd QuarterScoreRBOU': '主隊第三節分數大小',
        'RBOthers-T23rd QuarterScoreRBOU': '客隊第三節分數大小',
        'RBOthers-T14th QuarterScoreRBOU': '主隊第四節分數大小',
        'RBOthers-T24th QuarterScoreRBOU': '客隊第四節分數大小',
        'RBOthers-T1HalfScoreRBOdd/Even': '主隊半場單雙',
        'RBOthers-T2HalfScoreRBOdd/Even': '客隊半場單雙',
        'RBOthers-T1 2ndQuarterScoreRBOdd/Even': '主隊第二節分數單雙',
        'RBOthers-T2 2ndQuarterScoreRBOdd/Even': '客隊第二節分數單雙',
        'RBOthers-T1 3rdQuarterScoreRBOdd/Even': '主隊第三節分數單雙',
        'RBOthers-T2 3rdQuarterScoreRBOdd/Even': '客隊第三節分數單雙',
        'RBOthers-T1 4thQuarterScoreRBOdd/Even': '主隊第四節分數單雙',
        'RBOthers-T2 4thQuarterScoreRBOdd/Even': '客隊第四節分數單雙',
        'RBOthers-CardRBHA': '紅黃牌讓分',
        'RBOthers-CardRBOU': '紅黃牌大小',
        'RBOthers-CornerRBHA': '角球讓分',
        'RBOthers-CornerRBOU': '角球大小',
        'RBOthers-HalfCornerRBHA': '上半角球讓分',
        'RBOthers-HalfCardRBHA': '上半罰牌讓分',
        'RBOthers-T1CornerRBScore': '主隊角球',
        'RBOthers-T2CornerRBScore': '客隊角球',
        'RBOthers-RBCorrect Score': '正確比分',
        'RBOthers-T1 RBScore': '主隊總得分',
        'RBOthers-T2 RBScore': '客隊總得分',
        'RBOthers-TotalHitRBOU': '安打總數',
        'RBOthers-1st SetGameRBHA': '第一局讓分(網球)',
        'RBOthers-2nd SetGameRBHA': '第二局讓分(網球)',
        'RBOthers-3rd SetGameRBHA': '第三局讓分(網球)',
        'RBOthers-4th SetGameRBHA': '第四局讓分(網球)',
        'RBOthers-5th SetGameRBHA': '第五局讓分(網球)',
        'RBOthers-6th SetGameRBHA': '第六局讓分(網球)',
        'RBOthers-7th SetGameRBHA': '第七局讓分(網球)',
        'RBOthers-1st PointRBHA': '第一局讓分(桌球、排球)',
        'RBOthers-2nd PointRBHA': '第二局讓分(桌球、排球)',
        'RBOthers-3rd PointRBHA': '第三局讓分(桌球、排球)',
        'RBOthers-4th PointRBHA': '第四局讓分(桌球、排球)',
        'RBOthers-5 PointRBHA': '第五局讓分(桌球、排球)',
        'RBOthers-6 PointRBHA': '第六局讓分(桌球、排球)',
        'RBOthers-7 PointRBHA': '第七局讓分(桌球、排球)',
        'RBOthers-1st SetGameRBOU': '第一局大小(網球)',
        'RBOthers-2nd SetGameRBOU': '第二局大小(網球)',
        'RBOthers-3rd SetGameRBOU': '第三局大小(網球)',
        'RBOthers-4th SetGameRBOU': '第四局大小(網球)',
        'RBOthers-5th SetGameRBOU': '第五局大小(網球)',
        'RBOthers-6th SetGameRBOU': '第六局大小(網球)',
        'RBOthers-7th SetGameRBOU': '第七局大小(網球)',
        'RBOthers-PointRBOU': '大小(桌球、排球)',
        'RBOthers-1st PointRBOU': '第一局大小(桌球、排球)',
        'RBOthers-2nd PointRBOU': '第二局大小(桌球、排球)',
        'RBOthers-3rd PointRBOU': '第三局大小(桌球、排球)',
        'RBOthers-4th PointRBOU': '第四局大小(桌球、排球)',
        'RBOthers-5 PointRBOU': '第五局大小(桌球、排球)',
        'RBOthers-6 PointRBOU': '第六局大小(桌球、排球)',
        'RBOthers-7 PointRBOU': '第七局大小(桌球、排球)',
        'RBOthers-GameRBHA': '讓分(網球)',
        'RBOthers-PointRBHA': '讓分(桌球、排球)',
        'RBOthers-GameRBOU': '大小(網球)',
        'RBOthers-1st MapRBHA': '第一張地圖讓分',
        'RBOthers-2nd MapRBHA': '第二張地圖讓分',
        'RBOthers-3rd MapRBHA': '第三張地圖讓分',
        'RBOthers-4th MapRBHA': '第四張地圖讓分',
        'RBOthers-5th MapRBHA': '第五張地圖讓分',
        'RBOthers-6th MapRBHA': '第六張地圖讓分',
        'RBOthers-7th MapRBHA': '第七張地圖讓分',
        'RBOthers-1st MapRBOU': '第一張地圖大小',
        'RBOthers-2nd MapRBOU': '第二張地圖大小',
        'RBOthers-3rd MapRBOU': '第三張地圖大小',
        'RBOthers-4th MapRBOU': '第四張地圖大小',
        'RBOthers-5th MapRBOU': '第五張地圖大小',
        'RBOthers-6th MapRBOU': '第六張地圖大小',
        'RBOthers-7th MapRBOU': '第七張地圖大小'
    }
}